PROTOCOL_ISSUE_CODE_CATALOG_VERSION = "v1"


# Gatekeeper issue codes
WF_EMPTY_STEPS = "WF_EMPTY_STEPS"
STEP_INVALID_IO_HEADER = "STEP_INVALID_IO_HEADER"
STEP_DUPLICATE_ID = "STEP_DUPLICATE_ID"
STEP_INVALID_ACTION = "STEP_INVALID_ACTION"
STEP_MISSING_OUTPUT = "STEP_MISSING_OUTPUT"
STEP_INPUT_TEMPLATE_RESIDUE = "STEP_INPUT_TEMPLATE_RESIDUE"
STEP_INPUT_UNBOUND = "STEP_INPUT_UNBOUND"
STEP_OUTPUT_TEMPLATE_RESIDUE = "STEP_OUTPUT_TEMPLATE_RESIDUE"
STEP_ON_REJECT_TARGET_MISSING = "STEP_ON_REJECT_TARGET_MISSING"
STEP_ON_REJECT_NOT_BACKWARD = "STEP_ON_REJECT_NOT_BACKWARD"
WF_UNKNOWN_ACTIONS = "WF_UNKNOWN_ACTIONS"

# 结构化构件校验错误码（预留，供 Generator 结构化路径使用）
WF_STRUCTURED_ARTIFACT_INVALID = "WF_STRUCTURED_ARTIFACT_INVALID"


# Dry-run issue codes
DRY_RUN_MISSING_INPUTS = "DRY_RUN_MISSING_INPUTS"
DRY_RUN_STEP_SKIPPED = "DRY_RUN_STEP_SKIPPED"
DRY_RUN_STEP_INPUT_ASSERT_FAILED = "DRY_RUN_STEP_INPUT_ASSERT_FAILED"
DRY_RUN_STEP_OUTPUT_ASSERT_FAILED = "DRY_RUN_STEP_OUTPUT_ASSERT_FAILED"
DRY_RUN_UNDEFINED_VARIABLES = "DRY_RUN_UNDEFINED_VARIABLES"


# Security scan issue codes
SECURITY_SCAN_VIOLATION = "SECURITY_SCAN_VIOLATION"
SECURITY_SCAN_CONFIRM_MISSING = "SECURITY_SCAN_CONFIRM_MISSING"


# Service / registry surface issue codes
WF_PARSE_FAILED = "WF_PARSE_FAILED"
ENTRY_RESOLVE_FAILED = "ENTRY_RESOLVE_FAILED"
ENTRY_FILE_MISSING = "ENTRY_FILE_MISSING"
DSL_LEGACY_ON_REJECT_DEPRECATED = "DSL_LEGACY_ON_REJECT_DEPRECATED"


GATEKEEPER_ISSUE_CODES = (
    WF_EMPTY_STEPS,
    STEP_INVALID_IO_HEADER,
    STEP_DUPLICATE_ID,
    STEP_INVALID_ACTION,
    STEP_MISSING_OUTPUT,
    STEP_INPUT_TEMPLATE_RESIDUE,
    STEP_INPUT_UNBOUND,
    STEP_OUTPUT_TEMPLATE_RESIDUE,
    STEP_ON_REJECT_TARGET_MISSING,
    STEP_ON_REJECT_NOT_BACKWARD,
    WF_UNKNOWN_ACTIONS,
    WF_STRUCTURED_ARTIFACT_INVALID,
)

DRY_RUN_ISSUE_CODES = (
    DRY_RUN_MISSING_INPUTS,
    DRY_RUN_STEP_SKIPPED,
    DRY_RUN_STEP_INPUT_ASSERT_FAILED,
    DRY_RUN_STEP_OUTPUT_ASSERT_FAILED,
    DRY_RUN_UNDEFINED_VARIABLES,
)

SECURITY_SCAN_ISSUE_CODES = (
    SECURITY_SCAN_VIOLATION,
    SECURITY_SCAN_CONFIRM_MISSING,
)

SERVICE_AND_REGISTRY_ISSUE_CODES = (
    WF_PARSE_FAILED,
    ENTRY_RESOLVE_FAILED,
    ENTRY_FILE_MISSING,
    DSL_LEGACY_ON_REJECT_DEPRECATED,
)


def protocol_issue_code_catalog() -> dict[str, tuple[str, ...]]:
    return {
        "version": (PROTOCOL_ISSUE_CODE_CATALOG_VERSION,),
        "gatekeeper": GATEKEEPER_ISSUE_CODES,
        "dry_run": DRY_RUN_ISSUE_CODES,
        "security_scan": SECURITY_SCAN_ISSUE_CODES,
        "service_registry": SERVICE_AND_REGISTRY_ISSUE_CODES,
    }


def all_protocol_issue_codes() -> tuple[str, ...]:
    seen: set[str] = set()
    ordered: list[str] = []
    for group in (
        GATEKEEPER_ISSUE_CODES,
        DRY_RUN_ISSUE_CODES,
        SECURITY_SCAN_ISSUE_CODES,
        SERVICE_AND_REGISTRY_ISSUE_CODES,
    ):
        for code in group:
            if code in seen:
                continue
            seen.add(code)
            ordered.append(code)
    return tuple(ordered)
