"""Champion 业务逻辑编排模块。

通过 ExecutionHooks 注入 Runner，管理 Meta Workflow 的工作流复用、
评审、注册和回放逻辑。Runner 本身不知道任何 Champion 语义。

步骤 ID 常量（Meta Workflow 固定结构）：
  Step 1 — Planner
  Step 2 — Designer  ← 复用时跳过
  Step 3 — Evaluator ← 复用时跳过
"""
from __future__ import annotations

import hashlib
import json
import logging
import os
import tempfile
from typing import Any

from agent.engine.execution_hooks import ExecutionHooks, StepHookResult

logger = logging.getLogger(__name__)

# Meta Workflow 步骤 ID 常量（修改步骤结构时同步更新）
_DESIGNER_STEP_ID = 2
_EVALUATOR_STEP_ID = 3


class ChampionTracker(ExecutionHooks):
    """Champion 业务逻辑编排器，通过 ExecutionHooks 四钩子驱动。

    唯一知道 Meta Workflow 业务语义的模块：
    - on_run_start:         复合指纹查找 + Champion 注水
    - on_step_before:       复用跳过判断（Designer / Evaluator）
    - on_step_after:        evaluator_report 处理 + Champion 更新
    - on_run_end:           工作流注册 + 回放 + 协议错误回流
    """

    def __init__(
        self,
        state_store,
        workflow_registry,
        protocol_service,
        workflows_root: str,
        index_path: str | None = None,
    ) -> None:
        self._state_store = state_store
        self._workflow_registry = workflow_registry
        self._protocol_service = protocol_service
        self._workflows_root = workflows_root
        self._index_path = index_path
        self._current_run_id: str | None = None

    # ── 钩子实现 ──────────────────────────────────────────────────────────────

    async def on_run_start(self, run_id: str, context: dict) -> None:
        """复合指纹查找：requirement_fingerprint + blueprint_fingerprint。

        若找到已有 APPROVED champion，注水到 context 并设置 __reuse_champion__。
        """
        self._current_run_id = run_id
        req_fp = self._requirement_fingerprint(context)
        bp_fp = self._blueprint_fingerprint(context)
        if not req_fp or not bp_fp:
            return
        matched = await self._state_store.load_latest_champion_by_composite(req_fp, bp_fp)
        if matched:
            logger.info("🏆 找到复合指纹匹配的 Champion，执行注水。")
            self._hydrate_champion_context(context, matched)

    async def on_step_before(self, step: dict, context: dict) -> StepHookResult:
        """复用跳过判断：__reuse_champion__ 为 True 时跳过 Designer/Evaluator。"""
        step_id = step.get("id")
        if step_id == _EVALUATOR_STEP_ID and context.get("final_artifact"):
            protocol_errors = self._check_protocol_errors(context.get("final_artifact"), context)
            if protocol_errors:
                self._replace_prev_defects(context, protocol_errors, source="evaluator_precheck")
                logger.warning(
                    "⚠️  [Step %s] Evaluator 前置协议体检发现 %d 项缺陷，已注入 prev_defects。",
                    step_id,
                    len(protocol_errors),
                )

        if not context.get("__reuse_champion__"):
            return StepHookResult()
        # Designer（Step 2）：有 final_artifact 才跳过
        if step_id == _DESIGNER_STEP_ID and context.get("final_artifact"):
            logger.info("♻️  [Step %s] 复用 Champion，跳过 Designer。", step_id)
            return StepHookResult(skip=True)
        # Evaluator（Step 3）：直接跳过
        if step_id == _EVALUATOR_STEP_ID:
            logger.info("♻️  [Step %s] 复用 Champion，跳过 Evaluator。", step_id)
            return StepHookResult(skip=True)
        return StepHookResult()

    async def on_step_after(self, step: dict, output: dict, context: dict) -> None:
        """处理 evaluator_report 输出：更新 Champion 记录。"""
        raw = output.get("evaluator_report")
        if raw is None:
            return
        report = _parse_report(raw)
        await self._update_champion(context, report)

    async def on_run_end(self, run_id: str, context: dict) -> None:
        """工作流完成：注册 + 回放 + 协议错误回流。"""
        if context.get("__skip_auto_replay__"):
            return

        artifact = context.get("final_artifact")
        if not artifact:
            return

        report = _parse_report(context.get("evaluator_report"))
        if report.get("status") != "APPROVED":
            return

        artifact_for_engine = (
            artifact.to_markdown() if hasattr(artifact, "to_markdown") else artifact
        )

        # 预检：获取 ProtocolReport 对象以便调用 errors_as_defects()
        protocol_errors = self._check_protocol_errors(artifact_for_engine, context)
        if protocol_errors:
            self._replace_prev_defects(context, protocol_errors, source="register_precheck")
            logger.warning("⚠️ 工作流注册预检失败，协议错误已回流 prev_defects：%d 项", len(protocol_errors))
            return

        # 注册（写入磁盘 + 更新索引）
        try:
            reg_info = self._workflow_registry.register_generated_workflow(
                artifact=artifact_for_engine,
                description=context.get("requirement", "generated by meta workflow"),
                registered_skills=context.get("registered_skills", []),
                available_context=context,
            )
        except Exception as exc:
            logger.error("❌ 工作流注册失败：%s", exc)
            self._replace_prev_defects(context, [{
                "location": "workflow:registration",
                "type": "PROTOCOL_ERROR",
                "code": "WF_PARSE_FAILED",
                "fix_category": "model-fixable",
                "reason": str(exc),
                "suggestion": "请检查工作流语法和协议合规性。",
            }], source="registration_exception")
            return

        # 写入 context 注册审计信息
        context["workflow_id"] = reg_info["workflow_id"]
        context["generated_workflow_path"] = reg_info["workflow_path"]
        context["generated_workflow_registration_summary"] = reg_info.get("protocol_summary", "ok")
        context["generated_workflow_protocol_report"] = reg_info.get("protocol_report", {})
        context["generated_workflow_dry_run"] = reg_info.get("dry_run", {"status": "skipped"})

        # 持久化注册审计
        await self._state_store.save_run_meta(
            run_id,
            registration_audit={
                "workflow_id": reg_info.get("workflow_id"),
                "workflow_path": reg_info.get("workflow_path"),
                "protocol_summary": reg_info.get("protocol_summary", "ok"),
                "protocol_report": reg_info.get("protocol_report", {}),
                "dry_run": reg_info.get("dry_run", {"status": "skipped"}),
            },
        )

        # 回放生成的工作流
        await self._attempt_replay(reg_info["workflow_path"], context)

    # ── 私有方法 ──────────────────────────────────────────────────────────────

    @staticmethod
    def _requirement_fingerprint(context: dict) -> str:
        """计算 requirement 字段的 SHA-256 指纹。"""
        requirement = str(context.get("requirement", "") or "").strip()
        if not requirement:
            return ""
        return hashlib.sha256(requirement.encode("utf-8")).hexdigest()

    @staticmethod
    def _extract_blueprint_features(context: dict) -> dict | None:
        """从 context 中提取 workflow_blueprint 的结构化特征。"""
        raw = context.get("workflow_blueprint")
        if raw is None:
            return None
        parsed: Any = raw
        if isinstance(raw, str):
            try:
                parsed = json.loads(raw)
            except json.JSONDecodeError:
                parsed = raw.strip()
        if not isinstance(parsed, dict):
            return {"raw_blueprint": str(parsed)}
        steps = parsed.get("main_flow_steps", [])
        step_features = []
        if isinstance(steps, list):
            for step in steps:
                if not isinstance(step, dict):
                    continue
                inputs = step.get("inputs") or {}
                outputs = step.get("outputs") or {}
                step_features.append({
                    "name": step.get("name"),
                    "action": step.get("action"),
                    "inputs": sorted(inputs.keys()) if isinstance(inputs, dict) else list(inputs),
                    "outputs": sorted(outputs.keys()) if isinstance(outputs, dict) else list(outputs),
                })
        return {
            "workflow_name": parsed.get("workflow_name") or parsed.get("name"),
            "step_count": len(step_features),
            "steps": step_features,
            "constraints": parsed.get("constraints", []),
        }

    @classmethod
    def _blueprint_fingerprint(cls, context: dict) -> str:
        """计算 blueprint 特征的 SHA-256 指纹。"""
        features = cls._extract_blueprint_features(context)
        if not features:
            return ""
        payload = json.dumps(features, ensure_ascii=False, sort_keys=True)
        return hashlib.sha256(payload.encode("utf-8")).hexdigest()

    @staticmethod
    def _report_score(report: dict) -> int:
        """从 evaluator_report 中提取数值分数，解析失败返回 -1。"""
        if not isinstance(report, dict):
            return -1
        try:
            return int(report.get("score", -1))
        except (TypeError, ValueError):
            return -1

    async def _update_champion(self, context: dict, report: dict) -> None:
        """根据评审报告更新 Champion 记录。

        - APPROVED 且分数 >= 当前 champion：写入新 champion
        - 其他情况：保留现有 champion，仅更新 feedback
        """
        run_id = self._current_run_id
        req_fp = self._requirement_fingerprint(context)
        bp_fp = self._blueprint_fingerprint(context)

        if report.get("status") != "APPROVED":
            await self._state_store.save_run_meta(
                run_id,
                champion_json=None,
                last_feedback=report.get("overall_feedback"),
                requirement_fingerprint=req_fp,
                blueprint_fingerprint=bp_fp,
            )
            return

        candidate = {
            "score": self._report_score(report),
            "final_artifact": context.get("final_artifact"),
            "evaluator_report": report,
            "blueprint_fingerprint": bp_fp,
            "blueprint_features": self._extract_blueprint_features(context),
        }
        existing_meta = await self._state_store.load_run_meta(run_id)
        existing_champion = (existing_meta or {}).get("champion_json") or {}
        existing_score = self._report_score(existing_champion.get("evaluator_report", {}))

        if candidate["score"] >= existing_score:
            await self._state_store.save_run_meta(
                run_id,
                champion_json=candidate,
                last_feedback=report.get("overall_feedback"),
                requirement_fingerprint=req_fp,
                blueprint_fingerprint=bp_fp,
            )
            context["champion_json"] = candidate
        else:
            await self._state_store.save_run_meta(
                run_id,
                champion_json=None,
                last_feedback=report.get("overall_feedback"),
                requirement_fingerprint=req_fp,
                blueprint_fingerprint=bp_fp,
            )
            context["champion_json"] = existing_champion

        context["last_feedback"] = report.get("overall_feedback")
        context["handoff_artifact"] = {
            "champion_json": context.get("champion_json"),
            "last_feedback": context.get("last_feedback"),
        }

    @staticmethod
    def _hydrate_champion_context(context: dict, run_meta: dict) -> None:
        """将 Champion 数据注水到 context，并标记 __reuse_champion__。"""
        if not run_meta:
            return
        champion = run_meta.get("champion_json")
        feedback = run_meta.get("last_feedback")
        registration_audit = run_meta.get("registration_audit")
        context["champion_json"] = champion
        context["last_feedback"] = feedback
        if registration_audit:
            context["generated_workflow_registration_audit"] = registration_audit
        context["handoff_artifact"] = {
            "champion_json": champion,
            "last_feedback": feedback,
        }
        if isinstance(champion, dict):
            report = champion.get("evaluator_report", {})
            if report.get("status") == "APPROVED" and champion.get("final_artifact"):
                context["final_artifact"] = champion["final_artifact"]
                context["evaluator_report"] = report
                context["__reuse_champion__"] = True

    def _check_protocol_errors(self, artifact: Any, context: dict) -> list[dict]:
        """预检 artifact，返回协议错误 defect 列表（空列表表示通过）。

        解析 artifact → WorkflowModel，运行 Gatekeeper + DryRun，
        调用 errors_as_defects() 获取结构化错误列表。
        """
        from agent.engine.protocol.normalizer import sanitize_artifact_for_engine
        from agent.engine.protocol.report import ProtocolReport

        artifact_text = artifact.to_markdown() if hasattr(artifact, "to_markdown") else artifact
        sanitized = sanitize_artifact_for_engine(artifact_text)
        tmp_fd, tmp_path = tempfile.mkstemp(suffix=".step.md")
        try:
            with os.fdopen(tmp_fd, "w", encoding="utf-8") as f:
                f.write(sanitized)
            try:
                workflow_model, _ = self._protocol_service.parse_workflow_file(tmp_path)
            except Exception as exc:
                return [{
                    "location": "workflow:parse",
                    "type": "PROTOCOL_ERROR",
                    "reason": f"解析失败：{exc}",
                    "suggestion": "请检查工作流 Markdown 格式。",
                }]
            gk_report, dry_run_result = self._protocol_service.pre_register_check(
                workflow_model,
                registered_skills=context.get("registered_skills"),
                available_context=context,
            )
            combined = ProtocolReport()
            combined.merge(gk_report)
            combined.merge(dry_run_result.report)
            return combined.errors_as_defects() if combined.has_errors() else []
        finally:
            try:
                os.unlink(tmp_path)
            except OSError:
                pass

    @staticmethod
    def _replace_prev_defects(context: dict, defects: list[dict], source: str) -> None:
        latest = ChampionTracker._dedupe_defects(list(defects or []))
        previous = ChampionTracker._dedupe_defects(list(context.get("prev_defects") or []))
        context["prev_defects"] = latest
        context["prev_defects_summary"] = {
            "source": source,
            "previous_count": len(previous),
            "latest_count": len(latest),
            "latest_types": sorted({str(d.get("type") or "UNKNOWN") for d in latest}),
        }

    @staticmethod
    def _dedupe_defects(defects: list[dict]) -> list[dict]:
        seen: set[tuple[str, str, str]] = set()
        result: list[dict] = []
        for defect in defects:
            location = str(defect.get("location") or "")
            defect_type = str(defect.get("type") or "")
            reason = str(defect.get("reason") or "")
            key = (location, defect_type, reason)
            if key in seen:
                continue
            seen.add(key)
            result.append(defect)
        return result

    async def _attempt_replay(self, workflow_path: str, context: dict) -> None:
        """在内存 DB 中回放生成的工作流，验证其可执行性。"""
        from agent.engine.protocol.infer_inputs import with_runtime_input_defaults

        workflow_model, _ = self._protocol_service.parse_workflow_file(workflow_path)
        required_inputs = self._protocol_service.infer_required_inputs(workflow_model)
        replay_context = with_runtime_input_defaults(context)
        missing = [x for x in required_inputs if x not in replay_context]
        if missing:
            context["generated_workflow_replay"] = {
                "status": "skipped",
                "missing_inputs": missing,
            }
            logger.info("⏭️  回放跳过（缺少输入）：%s", missing)
            return

        # 延迟导入避免潜在循环依赖
        from agent.engine.runner import Runner  # type: ignore[import-not-found]

        replay_context["__skip_auto_replay__"] = True
        replay_runner = Runner(
            filepath=workflow_path,
            initial_context=replay_context,
            db_path=":memory:",
        )
        try:
            replay_result = await replay_runner.run()
            context["generated_workflow_replay"] = {
                "status": replay_result.get("status", "unknown"),
                "run_id": replay_result.get("run_id"),
            }
            logger.info("✅ 工作流回放完成，状态：%s", replay_result.get("status"))
        except Exception as exc:
            context["generated_workflow_replay"] = {
                "status": "failed",
                "error": str(exc),
            }
            logger.warning("⚠️ 工作流回放失败：%s", exc)


# ── 模块级工具函数 ─────────────────────────────────────────────────────────────

def _parse_report(raw: Any) -> dict:
    """统一解析 evaluator_report：dict 直接返回，str 尝试 JSON 解析。"""
    if isinstance(raw, dict):
        return raw
    if isinstance(raw, str):
        try:
            return json.loads(raw)
        except json.JSONDecodeError:
            logger.warning("⚠️ evaluator_report 无法解析为 JSON，忽略。")
    return {}
